language: node_js

node_js:
  - "stable"
  - "6"

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - npm run report-coverage -- -e TRAVIS_NODE_VERSION

script:
  - npm run test

branches:
  only:
    - master
    - /^v[0-9].*$/

